
import localFont from "next/font/local";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Footer from "@/components/Footer";
import Header from "@/components/Header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className='md:flex md:gap-0 '>
          <div className='md:w-[270px] md:mr-5'>
            <Sidebar></Sidebar>
          </div>
          <div className='w-full h-[100%] bg-gray-100'>
            <Header></Header>
            <div className=' w-full '>
              {children}
            </div>
              <Footer></Footer>
          </div>
        </div>
      </body>
    </html>
  );
}
